#!/usr/bin/env bash
# Tests for lib/flags.sh: the command-line decision surface — flag
# accept/reject, the non-interactive inference, the --set pending map and
# its key filter, and the missing/unconsumed decision bookkeeping.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1
. tests/lib.sh
. lib/term.sh
. lib/values.sh
. lib/flags.sh

# reset_flags — a clean flag state between cases (the libs keep state in
# globals; parse_install_flags is not idempotent by itself).
reset_flags() {
	NON_INTERACTIVE=0
	FLAG_PROFILE=""
	FLAG_EXPOSURE=""
	FLAG_IDP=""
	FLAG_ADMIN_EMAIL=""
	FLAG_ADMIN_EMAIL_USED=0
	FLAG_CHAT_REPO=""
	COMPONENTS_SPEC=""
	unset PENDING
	declare -gA PENDING=()
	MISSING_DECISIONS=()
}

# ---- accept: the whole surface at once
reset_flags
parse_install_flags --pystino /some/pystino --profile team --exposure edge \
	--idp authelia --admin-email op@example.org --chat-repo /some/cerea \
	--components redaction=pattern,fetch=direct,metering=on \
	--set PUBLIC_HOST=cerea.example --set ACME_EMAIL=acme@example.org \
	--dry-run --phase2 --build
assert_eq "profile accepted" "team" "$FLAG_PROFILE"
assert_eq "exposure accepted" "edge" "$FLAG_EXPOSURE"
assert_eq "idp accepted" "authelia" "$FLAG_IDP"
assert_eq "admin email accepted" "op@example.org" "$FLAG_ADMIN_EMAIL"
assert_eq "chat repo accepted" "/some/cerea" "$FLAG_CHAT_REPO"
assert_eq "components spec kept raw" "redaction=pattern,fetch=direct,metering=on" "$COMPONENTS_SPEC"
assert_eq "switches parsed" "1/1/1" "$DRY_RUN/$PHASE2_ONLY/$BUILD"
assert_eq "pystino parsed" "/some/pystino" "$CLI_PYSTINO"
assert_eq "--set pairs land in PENDING" "cerea.example" "${PENDING[PUBLIC_HOST]}"
assert_eq "--set second pair lands too" "acme@example.org" "${PENDING[ACME_EMAIL]}"
reset_flags
parse_install_flags --set TLS_DIRECTIVE=
assert_ok "--set KEY= (empty value) is accepted" pending_has TLS_DIRECTIVE
assert_eq "--set empty value stays empty" "" "${PENDING[TLS_DIRECTIVE]}"
assert_eq "any decision flag implies non-interactive" "1" "$NON_INTERACTIVE"

# ---- the non-interactive inference: inputs and switches are not decisions
reset_flags
parse_install_flags --pystino /x --dry-run --phase2 --build --chat-repo /y
assert_eq "input/switch flags alone keep interactive mode" "0" "$NON_INTERACTIVE"
reset_flags
parse_install_flags --non-interactive
assert_eq "--non-interactive forces the mode" "1" "$NON_INTERACTIVE"
for f in "--profile team" "--exposure edge" "--idp house" "--admin-email a@b.c"; do
	reset_flags
	parse_install_flags $f
	assert_eq "$f alone implies non-interactive" "1" "$NON_INTERACTIVE"
done
reset_flags
parse_install_flags --set PUBLIC_HOST=x
assert_eq "--set alone implies non-interactive" "1" "$NON_INTERACTIVE"

# ---- reject: bad values fail with the vocabulary in the message
reset_flags
assert_fails_with "unknown profile rejected" "homelab|team|enterprise|satellite|generic" parse_install_flags --profile bogus
reset_flags
assert_fails_with "unknown exposure rejected — the menu has no lan/loopback" "edge|proxy" parse_install_flags --exposure lan
reset_flags
assert_fails_with "unknown idp word rejected" "house|external|custom|central|authelia|keycloak" parse_install_flags --idp saml
reset_flags
assert_fails_with "empty --admin-email rejected" "must not be empty" parse_install_flags --admin-email ""
reset_flags
assert_fails_with "malformed --set rejected" "not KEY=VALUE" parse_install_flags --set NOVALUE
reset_flags
assert_fails_with "unknown --set key rejected" "unknown deploy/.env key" parse_install_flags --set NOT_A_REAL_KEY=1
reset_flags
assert_fails_with "generated key rejected with the reason" "generated by the installer" parse_install_flags --set GATEWAY_SECRET_KEY=x
reset_flags
assert_fails_with "fixed key rejected with the reason" "fixed or derived" parse_install_flags --set POSTGRES_USER=chat
reset_flags
assert_fails_with "component-derived key rejected, --components named" "--components" parse_install_flags --set FETCH_BACKEND=direct
reset_flags
assert_fails_with "newline in a --set value rejected" "single-line" parse_install_flags --set PUBLIC_HOST=$'a\nb'
reset_flags
assert_fails_with "bad component word rejected with the vocabulary" "outside the vocabulary" parse_install_flags --components redaction=sideways
reset_flags
assert_fails_with "duplicate component key rejected" "twice" parse_install_flags --components redaction=off,redaction=ner
reset_flags
assert_fails_with "missing --profile value rejected" "needs a value" parse_install_flags --profile
reset_flags
assert_fails_with "the derived COMPOSE_PROFILES key rejected" "derived from the install shape" parse_install_flags --set COMPOSE_PROFILES=chat
reset_flags
assert_fails_with "the derived local-link key rejected" "derived from the install shape" parse_install_flags --set GATEWAY_OIDC__LINK_LOCAL_BY_EMAIL=true
reset_flags
assert_fails_with "the operator email rejected — --admin-email carries it" "--admin-email" parse_install_flags --set IDP_ADMIN_EMAIL=op@example.org

# ---- unknown argument keeps its exit code and usage
reset_flags
run_capture parse_install_flags --bogus
assert_eq "unknown argument exits 2" "2" "$RC"
assert_contains "unknown argument prints usage" "--components" "$OUT"

# ---- --set semantics: last wins, identifier enforced
reset_flags
parse_install_flags --set PUBLIC_HOST=first --set PUBLIC_HOST=second
assert_eq "repeated --set: last value wins" "second" "${PENDING[PUBLIC_HOST]}"
reset_flags
assert_fails_with "non-identifier --set key rejected" "not a valid variable name" parse_install_flags --set 2BAD=1

# ---- pending helpers
reset_flags
PENDING[KEY_A]=val
assert_ok "pending_has finds a set key" pending_has KEY_A
run_capture pending_has KEY_MISSING
assert_eq "pending_has fails for an absent key" "1" "$RC"
PENDING[EMPTY_KEY]=
assert_ok "pending_has honours set-but-empty" pending_has EMPTY_KEY
PENDING[KEY_B]=taken
pending_take KEY_B
assert_eq "pending_take returns the value" "taken" "$REPLY_VAL"
run_capture pending_has KEY_B
assert_eq "pending_take consumes the key" "1" "$RC"

# ---- missing-decision bookkeeping
reset_flags
record_missing PUBLIC_HOST "the host (supply with --set PUBLIC_HOST=VALUE)"
record_missing ACME_EMAIL "the ACME email (supply with --set ACME_EMAIL=VALUE)"
assert_fails_with "fail_missing_decisions names every missing key" "ACME_EMAIL" fail_missing_decisions
reset_flags
run_capture fail_missing_decisions
assert_eq "no missing decisions is a no-op" "0" "$RC"

# ---- unconsumed bookkeeping
reset_flags
PENDING[CHAT_OCR_MODEL]=m
assert_fails_with "an unconsumed --set is named" "never consumed" fail_unconsumed
reset_flags
FLAG_ADMIN_EMAIL=a@b.c
assert_fails_with "an unconsumed --admin-email is named" "--admin-email a@b.c" fail_unconsumed
reset_flags
FLAG_ADMIN_EMAIL=a@b.c
FLAG_ADMIN_EMAIL_USED=1
run_capture fail_unconsumed
assert_eq "a consumed --admin-email is not flagged" "0" "$RC"

# ---- usage documents the surface
run_capture usage
assert_contains "usage names --profile" "--profile <name>" "$OUT"
assert_contains "usage names --set" "--set KEY=VALUE" "$OUT"
assert_contains "usage names --non-interactive" "--non-interactive" "$OUT"
assert_contains "usage names --public-host" "--public-host <h>" "$OUT"
assert_contains "usage names --central" "--central <url>" "$OUT"

# ---- the decision shortcuts: they inject into PENDING, so the ask sites'
# validation sees them; the shapes that never ask still fail unconsumed
reset_flags
parse_install_flags --public-host cerea.example
assert_eq "--public-host switches the mode" "1" "$NON_INTERACTIVE"
assert_eq "--public-host fills PUBLIC_HOST" "cerea.example" "${PENDING[PUBLIC_HOST]:-}"

reset_flags
parse_install_flags --https-port 9443
assert_eq "--https-port fills HTTPS_PORT" "9443" "${PENDING[HTTPS_PORT]:-}"
# fail() exits, so a rejection is proven in a subshell with its exit code.
# The rc is captured in one line because `|| true` (needed so set -e does
# not read the deliberate failure as ours — the block once lived below
# summary, and the file's exit code lied about having passed) would
# otherwise clobber $? before the assert reads it.
( parse_install_flags --https-port abc ) 2>/dev/null || rc=$?
assert_eq "--https-port rejects a non-numeric port" "1" "${rc:-0}"

reset_flags
parse_install_flags --acme-email ops@example.org
assert_eq "--acme-email fills ACME_EMAIL" "ops@example.org" "${PENDING[ACME_EMAIL]:-}"

reset_flags
parse_install_flags --central https://central.example
assert_eq "--central fills the backend base URL" "https://central.example" "${PENDING[OPENAI_BASE_URL]:-}"
assert_eq "--central fills the OIDC issuer" "https://central.example" "${PENDING[CHAT_OIDC_PROVIDER_URL]:-}"
parse_install_flags --central https://central.example --set CHAT_OIDC_PROVIDER_URL=https://other.example
assert_eq "an explicit --set after --central overrides the issuer" "https://other.example" "${PENDING[CHAT_OIDC_PROVIDER_URL]:-}"

summary "test-flags.sh"

