/// <reference lib="webworker" />
import {
	clampOutput,
	MOUNT_ROOT,
	PYODIDE_INDEX_PATH,
	safeMountName,
	type HostToWorker,
	type RunOutcome,
	type WorkerToHost,
} from "./protocol";
import { installNetworkGate } from "./gate";

/**
 * The one Pyodide runtime. Runs inside a dedicated module worker so runaway
 * code can be killed with Worker.terminate() without touching the tab, and so
 * the main thread never executes model-written code.
 *
 * The network gate is installed before anything else, including the Pyodide
 * import itself: the interpreter's own asset loads (wasm, stdlib, lockfile)
 * are same-origin /pyodide/ requests and pass through it, while everything a
 * user script or micropip might reach does not.
 */

type PyodideAPI = import("pyodide").PyodideAPI;

const scope = self as unknown as typeof globalThis & {
	postMessage: (message: WorkerToHost, transfer?: Transferable[]) => void;
};

installNetworkGate(scope);

let pyodidePromise: Promise<PyodideAPI> | null = null;
let stdoutBuffer: string[] = [];
let stderrBuffer: string[] = [];

function post(message: WorkerToHost, transfer?: Transferable[]): void {
	scope.postMessage(message, transfer ?? []);
}

async function getPyodide(): Promise<PyodideAPI> {
	if (!pyodidePromise) {
		post({ type: "loading" });
		pyodidePromise = (async () => {
			// The dist is served same-origin from static/pyodide/ (gitignored,
			// regenerated by scripts/sync_pyodide.mjs). The dynamic import must
			// stay opaque to Vite — the file is a static asset, not a bundle input.
			const indexURL = new URL(PYODIDE_INDEX_PATH, scope.location.origin).href;
			const { loadPyodide } = await import(/* @vite-ignore */ `${indexURL}pyodide.mjs`);
			const py = await loadPyodide({
				indexURL,
				lockFileURL: `${indexURL}pyodide-lock.json`,
				stdLibURL: `${indexURL}python_stdlib.zip`,
			});
			py.FS.mkdirTree(MOUNT_ROOT);
			// Output capture is per-run: runs are serialized, so module buffers
			// are unambiguous. Batched handlers coalesce per newline, which keeps
			// line-oriented output ordered without a callback per byte.
			py.setStdout({
				batched: (chunk: string) => {
					stdoutBuffer.push(chunk.endsWith("\n") ? chunk : `${chunk}\n`);
				},
			});
			py.setStderr({
				batched: (chunk: string) => {
					stderrBuffer.push(chunk.endsWith("\n") ? chunk : `${chunk}\n`);
				},
			});
			// Pin micropip to this origin: the default index (python.pyodide.org)
			// is unreachable behind the gate, and any wheels an operator wants
			// installable must be served under static/pyodide/wheels/.
			await py.runPythonAsync(
				[
					"try:",
					"    import micropip",
					`    micropip.set_index_urls("${PYODIDE_INDEX_PATH}wheels/")`,
					"except ImportError:",
					"    pass",
				].join("\n")
			);
			post({ type: "ready" });
			return py;
		})();
		pyodidePromise.catch(() => {
			// A failed load must not wedge every future request on a broken
			// promise: clear it so the next run retries from scratch.
			pyodidePromise = null;
		});
	}
	return pyodidePromise;
}

function drainBuffers(): { stdout: string; stderr: string } {
	const stdout = stdoutBuffer.join("");
	const stderr = stderrBuffer.join("");
	stdoutBuffer = [];
	stderrBuffer = [];
	return { stdout: clampOutput(stdout), stderr: clampOutput(stderr) };
}

function describeError(err: unknown): string {
	const message = err instanceof Error ? err.message : String(err ?? "unknown error");
	// PyProxy exceptions carry the Python traceback in `message`; releasing the
	// proxy afterwards keeps a raised-per-run exception from leaking memory.
	const proxy = err as { destroy?: () => void } | null | undefined;
	if (proxy && typeof proxy.destroy === "function") {
		try {
			proxy.destroy();
		} catch {
			// Already dead along with the interpreter state; nothing to do.
		}
	}
	return clampOutput(message || "unknown error");
}

function reprResult(value: unknown): string | undefined {
	if (value === undefined || value === null) return undefined;
	try {
		const text = String(value);
		return text === "" ? undefined : clampOutput(text);
	} catch {
		return "<unprintable result>";
	} finally {
		const proxy = value as { destroy?: () => void } | null;
		if (proxy && typeof proxy.destroy === "function") {
			try {
				proxy.destroy();
			} catch {
				// The repr already surfaced; the proxy cleanup is best effort.
			}
		}
	}
}

async function run(id: number, code: string): Promise<void> {
	stdoutBuffer = [];
	stderrBuffer = [];
	let outcome: RunOutcome;
	try {
		const py = await getPyodide();
		const result = await py.runPythonAsync(code);
		outcome = { ok: true, ...drainBuffers(), result: reprResult(result) };
	} catch (err) {
		outcome = { ok: false, ...drainBuffers(), error: describeError(err) };
	}
	post({ type: "result", id, ...outcome });
}

async function loadFiles(
	id: number,
	files: Array<{ name: string; data: ArrayBuffer | string }>
): Promise<void> {
	try {
		const py = await getPyodide();
		py.FS.mkdirTree(MOUNT_ROOT);
		const written: string[] = [];
		for (const file of files) {
			const name = safeMountName(file.name);
			if (!name) {
				post({
					type: "result",
					id,
					ok: false,
					stdout: "",
					stderr: "",
					error: `invalid file name: ${file.name}`,
				});
				return;
			}
			if (typeof file.data === "string") {
				py.FS.writeFile(`${MOUNT_ROOT}/${name}`, file.data);
			} else {
				if (file.data.byteLength > 50 * 1024 * 1024) {
					post({
						type: "result",
						id,
						ok: false,
						stdout: "",
						stderr: "",
						error: `${name} is larger than the 50 MB runtime cap`,
					});
					return;
				}
				py.FS.writeFile(`${MOUNT_ROOT}/${name}`, new Uint8Array(file.data));
			}
			written.push(`${MOUNT_ROOT}/${name}`);
		}
		post({ type: "filesLoaded", id, written });
	} catch (err) {
		post({
			type: "result",
			id,
			ok: false,
			stdout: "",
			stderr: "",
			error: describeError(err),
		});
	}
}

scope.onmessage = (event: MessageEvent<HostToWorker>) => {
	const data = event.data;
	if (!data || typeof data !== "object") return;
	if (data.type === "run") void run(data.id, data.code);
	if (data.type === "loadFiles") void loadFiles(data.id, data.files);
};
